services:
  app:
    build: .
    container_name: bulk-sms-app
    ports:
      - "8090:8090"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bulk-sms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sms_app
      MYSQL_USER: sms_user
      MYSQL_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  dbdata:
