services:
  app:
    build: .
    container_name: bulk-sms-app
    ports:
      - "8090:80"
    volumes:
      # Mount only specific files/directories instead of entire project
      - ./index.html:/var/www/html/index.html
      - ./send_sms.php:/var/www/html/send_sms.php
      - ./db.php:/var/www/html/db.php
      - ./.env:/var/www/html/.env
      # Don't mount vendor/ - let it stay from the Docker build
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bulk-sms-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sms_app
      MYSQL_USER: sms_user
      MYSQL_PASSWORD: password123
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  dbdata: